// PROJECT
export const RESET_FETCH_PROJECT_DETAILS_WATCHER = "RESET_FETCH_PROJECT_DETAILS_WATCHER";
export const FETCH_PROJECT_DETAILS_WATCHER = "FETCH_PROJECT_DETAILS_WATCHER";
export const SET_PROJECT_DETAILS_SUCCESS = "SET_PROJECT_DETAILS_SUCCESS";
export const SET_PROJECT_DETAILS_FAILURE = "SET_PROJECT_DETAILS_FAILURE";

export const RESET_CREATE_PROJECT_REQUEST = 'RESET_CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';



// TASK
export const RESET_FETCH_TASK_DETAILS_WATCHER = "RESET_FETCH_TASK_DETAILS_WATCHER";
export const FETCH_TASK_DETAILS_WATCHER = "FETCH_TASK_DETAILS_WATCHER";
export const SET_TASK_DETAILS_SUCCESS = "SET_TASK_DETAILS_SUCCESS";
export const SET_TASK_DETAILS_FAILURE = "SET_TASK_DETAILS_FAILURE";

export const RESET_CREATE_TASK_REQUEST = "RESET_CREATE_TASK_REQUEST";
export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";











export const FETCH_ACCESS_TOKEN_WATCHER = "FETCH_ACCESS_TOKEN_WATCHER";
export const SET_ACCESS_TOKEN_SUCCESS = "SET_ACCESS_TOKEN_SUCCESS";
export const SET_ACCESS_TOKEN_FAILURE = "SET_ACCESS_TOKEN_FAILURE";

export const RESET_LOGIN_WATCHER = "RESET_LOGIN_WATCHER";
export const LOGIN_WATCHER = "LOGIN_WATCHER";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_SUCCESS_PREFERENCES = "SET_LOGIN_SUCCESS_PREFERENCES";
export const SET_LOGIN_SUCCESS_WELCOME = "SET_LOGIN_SUCCESS_WELCOME";
export const SET_LOGIN_FAILURE = "SET_LOGIN_FAILURE";
export const SET_SPLASH_SCREEN_ANIMATION = "SET_SPLASH_SCREEN_ANIMATION";
export const SET_USER_DEVICE_ID = "SET_USER_DEVICE_ID";
export const SEND_USER_DEVICE_ID = "SEND_USER_DEVICE_ID";
export const SET_FCM_TOKEN = "SET_FCM_TOKEN";
export const SET_SHARPSPORTS_BETTOR_ID = "SET_SHARPSPORTS_BETTOR_ID";

export const SOCIAL_LOGIN_WATCHER = "SOCIAL_LOGIN_WATCHER";
export const SET_SOCIAL_LOGIN_SUCCESS = "SET_SOCIAL_LOGIN_SUCCESS";
export const SET_SOCIAL_LOGIN_FAILURE = "SET_SOCIAL_LOGIN_FAILURE";

export const RESET_FETCH_DELETE_ACCOUNT_WATCHER = "RESET_FETCH_DELETE_ACCOUNT_WATCHER";
export const FETCH_DELETE_ACCOUNT_WATCHER = "FETCH_DELETE_ACCOUNT_WATCHER";
export const SET_DELETE_ACCOUNT_SUCCESS = "SET_DELETE_ACCOUNT_SUCCESS";
export const SET_DELETE_ACCOUNT_FAILURE = "SET_DELETE_ACCOUNT_FAILURE";

export const RESET_FETCH_USER_DETAILS_WATCHER = "RESET_FETCH_USER_DETAILS_WATCHER";
export const FETCH_USER_DETAILS_WATCHER = "FETCH_USER_DETAILS_WATCHER";
export const SET_USER_DETAILS_SUCCESS = "SET_USER_DETAILS_SUCCESS";
export const SET_USER_DETAILS_FAILURE = "SET_USER_DETAILS_FAILURE";

export const RESET_FETCH_SPORTS_DETAILS_WATCHER = "RESET_FETCH_SPORTS_DETAILS_WATCHER";
export const FETCH_SPORTS_DETAILS_WATCHER = "FETCH_SPORTS_DETAILS_WATCHER";
export const UPDATE_SPORTS_DETAILS_STATEDATA = "UPDATE_SPORTS_DETAILS_STATEDATA";
export const SET_SPORTS_DETAILS_SUCCESS = "SET_SPORTS_DETAILS_SUCCESS";
export const SET_SPORTS_DETAILS_FAILURE = "SET_SPORTS_DETAILS_FAILURE";

export const UPDATE_PREFERENCES_WATCHER = "UPDATE_PREFERENCES_WATCHER";
export const UPDATE_PREFERENCES_SUCCESS = "UPDATE_PREFERENCES_SUCCESS";
export const UPDATE_PREFERENCES_FAILURE = "UPDATE_PREFERENCES_FAILURE";

export const SET_SELECTED_SPORTS = "SET_SELECTED_SPORTS";

export const RESET_FETCH_TEAMS_DETAILS_WATCHER = "RESET_FETCH_TEAMS_DETAILS_WATCHER";
export const FETCH_TEAMS_DETAILS_WATCHER = "FETCH_TEAMS_DETAILS_WATCHER";
export const SET_TEAMS_DETAILS_SUCCESS = "SET_TEAMS_DETAILS_SUCCESS";
export const SET_TEAMS_DETAILS_FAILURE = "SET_TEAMS_DETAILS_FAILURE";
export const SET_SELECTED_TEAMS = "SET_SELECTED_TEAMS";
export const UPDATE_TEAMS_DETAILS_STATEDATA = "UPDATE_TEAMS_DETAILS_STATEDATA";

export const RESET_FETCH_HOSTS_DETAILS_WATCHER = "RESET_FETCH_HOSTS_DETAILS_WATCHER";
export const FETCH_HOSTS_DETAILS_WATCHER = "FETCH_HOSTS_DETAILS_WATCHER";
export const SET_HOSTS_DETAILS_SUCCESS = "SET_HOSTS_DETAILS_SUCCESS";
export const SET_HOSTS_DETAILS_FAILURE = "SET_HOSTS_DETAILS_FAILURE";
export const SET_SELECTED_HOSTS = "SET_SELECTED_HOSTS";
export const UPDATE_HOSTS_DETAILS_STATEDATA = "UPDATE_HOSTS_DETAILS_STATEDATA";

export const RESET_FETCH_FEED_DETAILS_WATCHER = "RESET_FETCH_FEED_DETAILS_WATCHER";
export const FETCH_FEED_DETAILS_WATCHER = "FETCH_FEED_DETAILS_WATCHER";
export const SET_FEED_DETAILS_SUCCESS = "SET_FEED_DETAILS_SUCCESS";
export const SET_FEED_DETAILS_FAILURE = "SET_FEED_DETAILS_FAILURE";
export const UPDATE_FEED_PILLS_DATA = "UPDATE_FEED_PILLS_DATA";

export const RESET_FETCH_GAMES_DETAILS_WATCHER = "RESET_FETCH_GAMES_DETAILS_WATCHER";
export const FETCH_GAMES_DETAILS_WATCHER = "FETCH_GAMES_DETAILS_WATCHER";
export const SET_GAMES_DETAILS_SUCCESS = "SET_GAMES_DETAILS_SUCCESS";
export const SET_GAMES_DETAILS_FAILURE = "SET_GAMES_DETAILS_FAILURE";

export const RESET_FETCH_REFRESHBETS_DETAILS_WATCHER = "RESET_FETCH_REFRESHBETS_DETAILS_WATCHER";
export const FETCH_REFRESHBETS_DETAILS_WATCHER = "FETCH_REFRESHBETS_DETAILS_WATCHER";
export const SET_REFRESHBETS_DETAILS_SUCCESS = "SET_REFRESHBETS_DETAILS_SUCCESS";
export const SET_REFRESHBETS_DETAILS_FAILURE = "SET_REFRESHBETS_DETAILS_FAILURE";
export const SET_IS_RESYNC_INPROGRESS = "SET_IS_RESYNC_INPROGRESS";

export const RESET_FETCH_GAME_PICKS_DETAILS_WATCHER = "RESET_FETCH_GAME_PICKS_DETAILS_WATCHER";
export const FETCH_GAME_PICKS_DETAILS_WATCHER = "FETCH_GAME_PICKS_DETAILS_WATCHER";
export const SET_GAME_PICKS_DETAILS_SUCCESS = "SET_GAME_PICKS_DETAILS_SUCCESS";
export const SET_GAME_PICKS_DETAILS_FAILURE = "SET_GAME_PICKS_DETAILS_FAILURE";

export const FETCH_PROP_PICKS_DETAILS_WATCHER = "FETCH_PROP_PICKS_DETAILS_WATCHER";
export const SET_PROP_PICKS_DETAILS_SUCCESS = "SET_PROP_PICKS_DETAILS_SUCCESS";
export const SET_PROP_PICKS_DETAILS_FAILURE = "SET_PROP_PICKS_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_GAME_PICKS_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SPORT_GAME_PICKS_DETAILS_WATCHER";
export const FETCH_SINGLE_SPORT_GAME_PICKS_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_GAME_PICKS_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_GAME_PICKS_DETAILS_SUCCESS = "SET_SINGLE_SPORT_GAME_PICKS_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_GAME_PICKS_DETAILS_FAILURE = "SET_SINGLE_SPORT_GAME_PICKS_DETAILS_FAILURE";

export const SET_GAME_PICKS_FILTER = "SET_GAME_PICKS_FILTER";
export const RESET_GAME_PICKS_FILTER = "RESET_GAME_PICKS_FILTER";

export const FETCH_SINGLE_SPORT_PROP_PICKS_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_PROP_PICKS_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_PROP_PICKS_DETAILS_SUCCESS = "SET_SINGLE_SPORT_PROP_PICKS_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_PROP_PICKS_DETAILS_FAILURE = "SET_SINGLE_SPORT_PROP_PICKS_DETAILS_FAILURE";
export const SET_PROP_PICKS_FILTER = "SET_PROP_PICKS_FILTER";
export const RESET_PROP_PICKS_FILTER = "RESET_PROP_PICKS_FILTER";

export const RESET_FETCH_WATCH_DETAILS_WATCHER = "RESET_FETCH_WATCH_DETAILS_WATCHER";
export const FETCH_WATCH_DETAILS_WATCHER = "FETCH_WATCH_DETAILS_WATCHER";
export const SET_WATCH_DETAILS_SUCCESS = "SET_WATCH_DETAILS_SUCCESS";
export const SET_WATCH_DETAILS_FAILURE = "SET_WATCH_DETAILS_FAILURE";

export const RESET_FETCH_RADIO_DETAILS_WATCHER = "RESET_FETCH_RADIO_DETAILS_WATCHER";
export const FETCH_RADIO_DETAILS_WATCHER = "FETCH_RADIO_DETAILS_WATCHER";
export const SET_RADIO_DETAILS_SUCCESS = "SET_RADIO_DETAILS_SUCCESS";
export const SET_RADIO_DETAILS_FAILURE = "SET_RADIO_DETAILS_FAILURE";
export const UPDATE_RADIO_PLAYER_STATUS = "UPDATE_RADIO_PLAYER_STATUS";

export const FETCH_MORE_ARTICLES_WATCHER = "FETCH_MORE_ARTICLES_WATCHER";
export const SET_MORE_ARTICLES_SUCCESS = "SET_MORE_ARTICLES_SUCCESS";
export const SET_MORE_ARTICLES_FAILURE = "SET_MORE_ARTICLES_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_MORE_ARTICLES_WATCHER = "RESET_FETCH_SINGLE_SPORT_MORE_ARTICLES_WATCHER";
export const FETCH_SINGLE_SPORT_MORE_ARTICLES_WATCHER = "FETCH_SINGLE_SPORT_MORE_ARTICLES_WATCHER";
export const SET_SINGLE_SPORT_MORE_ARTICLES_SUCCESS = "SET_SINGLE_SPORT_MORE_ARTICLES_SUCCESS";
export const SET_SINGLE_SPORT_MORE_ARTICLES_FAILURE = "SET_SINGLE_SPORT_MORE_ARTICLES_FAILURE";

export const RESET_FETCH_SINGLE_TEAM_MORE_ARTICLES_WATCHER = "RESET_FETCH_SINGLE_TEAM_MORE_ARTICLES_WATCHER";
export const FETCH_SINGLE_TEAM_MORE_ARTICLES_WATCHER = "FETCH_SINGLE_TEAM_MORE_ARTICLES_WATCHER";
export const SET_SINGLE_TEAM_MORE_ARTICLES_SUCCESS = "SET_SINGLE_TEAM_MORE_ARTICLES_SUCCESS";
export const SET_SINGLE_TEAM_MORE_ARTICLES_FAILURE = "SET_SINGLE_TEAM_MORE_ARTICLES_FAILURE";

export const RESET_FETCH_SINGLE_VIDEO_MORE_ARTICLES_WATCHER = "RESET_FETCH_SINGLE_VIDEO_MORE_ARTICLES_WATCHER";
export const FETCH_SINGLE_VIDEO_MORE_ARTICLES_WATCHER = "FETCH_SINGLE_VIDEO_MORE_ARTICLES_WATCHER";
export const SET_SINGLE_VIDEO_MORE_ARTICLES_SUCCESS = "SET_SINGLE_VIDEO_MORE_ARTICLES_SUCCESS";
export const SET_SINGLE_VIDEO_MORE_ARTICLES_FAILURE = "SET_SINGLE_VIDEO_MORE_ARTICLES_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SPORT_DETAILS_WATCHER";
export const FETCH_SINGLE_SPORT_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_DETAILS_SUCCESS = "SET_SINGLE_SPORT_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_DETAILS_FAILURE = "SET_SINGLE_SPORT_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_TEAM_DETAILS_WATCHER = "RESET_FETCH_SINGLE_TEAM_DETAILS_WATCHER";
export const FETCH_SINGLE_TEAM_DETAILS_WATCHER = "FETCH_SINGLE_TEAM_DETAILS_WATCHER";
export const SET_SINGLE_TEAM_DETAILS_SUCCESS = "SET_SINGLE_TEAM_DETAILS_SUCCESS";
export const SET_SINGLE_TEAM_DETAILS_FAILURE = "SET_SINGLE_TEAM_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_HOST_DETAILS_WATCHER = "RESET_FETCH_SINGLE_HOST_DETAILS_WATCHER";
export const FETCH_SINGLE_HOST_DETAILS_WATCHER = "FETCH_SINGLE_HOST_DETAILS_WATCHER";
export const SET_SINGLE_HOST_DETAILS_SUCCESS = "SET_SINGLE_HOST_DETAILS_SUCCESS";
export const SET_SINGLE_HOST_DETAILS_FAILURE = "SET_SINGLE_HOST_DETAILS_FAILURE";

export const RESET_FETCH_SPORTBOOK_DETAILS_WATCHER = "RESET_FETCH_SPORTBOOK_DETAILS_WATCHER";
export const FETCH_SPORTBOOK_DETAILS_WATCHER = "FETCH_SPORTBOOK_DETAILS_WATCHER";
export const SET_SPORTBOOK_DETAILS_SUCCESS = "SET_SPORTBOOK_DETAILS_SUCCESS";
export const SET_SPORTBOOK_DETAILS_FAILURE = "SET_SPORTBOOK_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_GAME_PREVIEW_DETAILS_WATCHER = "RESET_FETCH_SINGLE_GAME_PREVIEW_DETAILS_WATCHER";
export const FETCH_SINGLE_GAME_PREVIEW_DETAILS_WATCHER = "FETCH_SINGLE_GAME_PREVIEW_DETAILS_WATCHER";
export const SET_SINGLE_GAME_PREVIEW_DETAILS_SUCCESS = "SET_SINGLE_GAME_PREVIEW_DETAILS_SUCCESS";
export const SET_SINGLE_GAME_PREVIEW_DETAILS_FAILURE = "SET_SINGLE_GAME_PREVIEW_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_GAME_GAME_LOG_DETAILS_WATCHER = "RESET_FETCH_SINGLE_GAME_GAME_LOG_DETAILS_WATCHER";
export const FETCH_SINGLE_GAME_GAME_LOG_DETAILS_WATCHER = "FETCH_SINGLE_GAME_GAME_LOG_DETAILS_WATCHER";
export const SET_SINGLE_GAME_GAME_LOG_DETAILS_SUCCESS = "SET_SINGLE_GAME_GAME_LOG_DETAILS_SUCCESS";
export const SET_SINGLE_GAME_GAME_LOG_DETAILS_FAILURE = "SET_SINGLE_GAME_GAME_LOG_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_GAMES_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SPORT_GAMES_DETAILS_WATCHER";
export const FETCH_SINGLE_SPORT_GAMES_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_GAMES_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_GAMES_DETAILS_SUCCESS = "SET_SINGLE_SPORT_GAMES_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_GAMES_DETAILS_FAILURE = "SET_SINGLE_SPORT_GAMES_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_BETS_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SPORT_BETS_DETAILS_WATCHER";
export const FETCH_SINGLE_SPORT_BETS_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_BETS_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_BETS_DETAILS_SUCCESS = "SET_SINGLE_SPORT_BETS_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_BETS_DETAILS_FAILURE = "SET_SINGLE_SPORT_BETS_DETAILS_FAILURE";

export const FETCH_SINGLE_GAME_STAT_DETAILS_WATCHER = "FETCH_SINGLE_GAME_STAT_DETAILS_WATCHER";
export const SET_SINGLE_GAME_STAT_DETAILS_SUCCESS = "SET_SINGLE_GAME_STAT_DETAILS_SUCCESS";
export const SET_SINGLE_GAME_STAT_DETAILS_FAILURE = "SET_SINGLE_GAME_STAT_DETAILS_FAILURE";

export const FETCH_SINGLE_GAME_RESULT_DETAILS_WATCHER = "FETCH_SINGLE_GAME_RESULT_DETAILS_WATCHER";
export const SET_SINGLE_GAME_RESULT_DETAILS_SUCCESS = "SET_SINGLE_GAME_RESULT_DETAILS_SUCCESS";
export const SET_SINGLE_GAME_RESULT_DETAILS_FAILURE = "SET_SINGLE_GAME_RESULT_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_VIDEO_DETAILS_WATCHER = "RESET_FETCH_SINGLE_VIDEO_DETAILS_WATCHER";
export const FETCH_SINGLE_VIDEO_DETAILS_WATCHER = "FETCH_SINGLE_VIDEO_DETAILS_WATCHER";
export const SET_SINGLE_VIDEO_DETAILS_SUCCESS = "SET_SINGLE_VIDEO_DETAILS_SUCCESS";
export const SET_SINGLE_VIDEO_DETAILS_FAILURE = "SET_SINGLE_VIDEO_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_ARTICLE_DETAILS_WATCHER = "RESET_FETCH_SINGLE_ARTICLE_DETAILS_WATCHER";
export const FETCH_SINGLE_ARTICLE_DETAILS_WATCHER = "FETCH_SINGLE_ARTICLE_DETAILS_WATCHER";
export const SET_SINGLE_ARTICLE_DETAILS_SUCCESS = "SET_SINGLE_ARTICLE_DETAILS_SUCCESS";
export const SET_SINGLE_ARTICLE_DETAILS_FAILURE = "SET_SINGLE_ARTICLE_DETAILS_FAILURE";

export const RESET_FETCH_SERVER_DOWN_DETAILS_WATCHER = "RESET_FETCH_SERVER_DOWN_DETAILS_WATCHER";
export const FETCH_SERVER_DOWN_DETAILS_WATCHER = "FETCH_SERVER_DOWN_DETAILS_WATCHER";
export const SET_SERVER_DOWN_DETAILS_SUCCESS = "SET_SERVER_DOWN_DETAILS_SUCCESS";
export const SET_SERVER_DOWN_DETAILS_FAILURE = "SET_SERVER_DOWN_DETAILS_FAILURE";

export const RESET_FETCH_PREFERENCES_DETAILS_WATCHER = "RESET_FETCH_PREFERENCES_DETAILS_WATCHER";
export const FETCH_PREFERENCES_DETAILS_WATCHER = "FETCH_PREFERENCES_DETAILS_WATCHER";
export const SET_PREFERENCES_DETAILS_SUCCESS = "SET_PREFERENCES_DETAILS_SUCCESS";
export const SET_PREFERENCES_DETAILS_FAILURE = "SET_PREFERENCES_DETAILS_FAILURE";

export const RESET_FETCH_BOOKMAKER_DETAILS_WATCHER = "RESET_FETCH_BOOKMAKER_DETAILS_WATCHER";
export const FETCH_BOOKMAKER_DETAILS_WATCHER = "FETCH_BOOKMAKER_DETAILS_WATCHER";
export const SET_BOOKMAKER_DETAILS_SUCCESS = "SET_BOOKMAKER_DETAILS_SUCCESS";
export const SET_BOOKMAKER_DETAILS_FAILURE = "SET_BOOKMAKER_DETAILS_FAILURE";

export const RESET_FETCH_STANDINGS_DETAILS_WATCHER = "RESET_FETCH_STANDINGS_DETAILS_WATCHER";
export const FETCH_STANDINGS_DETAILS_WATCHER = "FETCH_STANDINGS_DETAILS_WATCHER";
export const SET_STANDINGS_DETAILS_SUCCESS = "SET_STANDINGS_DETAILS_SUCCESS";
export const SET_STANDINGS_DETAILS_FAILURE = "SET_STANDINGS_DETAILS_FAILURE";

export const RESET_FETCH_SETTINGS_DETAILS_WATCHER = "RESET_FETCH_SETTINGS_DETAILS_WATCHER";
export const FETCH_SETTINGS_DETAILS_WATCHER = "FETCH_SETTINGS_DETAILS_WATCHER";
export const SET_SETTINGS_DETAILS_SUCCESS = "SET_SETTINGS_DETAILS_SUCCESS";
export const SET_SETTINGS_DETAILS_FAILURE = "SET_SETTINGS_DETAILS_FAILURE";
export const SET_SETTINGS_DETAILS_MESSAGE = "SET_SETTINGS_DETAILS_MESSAGE";
export const SET_FEED_VERSION = "SET_FEED_VERSION";
export const SET_FEED_VERSION_UPDATE_STATUS = "SET_FEED_VERSION_UPDATE_STATUS";

export const ADD_SETTINGS_DETAILS_WATCHER = "ADD_SETTINGS_DETAILS_WATCHER";
export const ADD_SETTINGS_DETAILS_SUCCESS = "ADD_SETTINGS_DETAILS_SUCCESS";
export const ADD_SETTINGS_DETAILS_FAILURE = "ADD_SETTINGS_DETAILS_FAILURE";
export const ADD_SETTINGS_DETAILS_MESSAGE = "ADD_SETTINGS_DETAILS_MESSAGE";

export const RESET_UPDATE_REGISTRATION_DETAILS_WATCHER = "RESET_UPDATE_REGISTRATION_DETAILS_WATCHER";
export const UPDATE_REGISTRATION_DETAILS_WATCHER = "UPDATE_REGISTRATION_DETAILS_WATCHER";
export const UPDATE_REGISTRATION_DETAILS_SUCCESS = "UPDATE_REGISTRATION_DETAILS_SUCCESS";
export const UPDATE_REGISTRATION_DETAILS_FAILURE = "UPDATE_REGISTRATION_DETAILS_FAILURE";
export const SET_REGISTRATION_INFORMATION = "SET_REGISTRATION_INFORMATION";
export const RESET_PASSWORD_DETAILS_WATCHER = "RESET_PASSWORD_DETAILS_WATCHER";
export const RESET_PASSWORD_DETAILS_SUCCESS = "RESET_PASSWORD_DETAILS_SUCCESS";
export const RESET_PASSWORD_DETAILS_FAILURE = "RESET_PASSWORD_DETAILS_FAILURE";

export const RESET_HOST_PREFERENCE_STATE = "RESET_HOST_PREFERENCE_STATE";
export const RESET_SPORT_PREFERENCE_STATE = "RESET_SPORT_PREFERENCE_STATE";
export const RESET_TEAM_PREFERENCE_STATE = "RESET_TEAM_PREFERENCE_STATE";

export const RESET_FETCH_NAVIGATION_ROUTE_DETAILS_WATCHER = "RESET_FETCH_NAVIGATION_ROUTE_DETAILS_WATCHER";
export const ADD_NAVIGATION_ROUTE_DETAILS_WATCHER = "ADD_NAVIGATION_ROUTE_DETAILS_WATCHER";
export const REMOVE_NAVIGATION_ROUTE_DETAILS_WATCHER = "REMOVE_NAVIGATION_ROUTE_DETAILS_WATCHER";
export const COPY_NAVIGATION_ROUTE_DETAILS_WATCHER = "COPY_NAVIGATION_ROUTE_DETAILS_WATCHER";

export const RESET_FETCH_PLAYER_CARD_DETAILS_WATCHER = "RESET_FETCH_PLAYER_CARD_DETAILS_WATCHER";
export const FETCH_PLAYER_CARD_DETAILS_WATCHER = "FETCH_PLAYER_CARD_DETAILS_WATCHER";
export const SET_PLAYER_CARD_DETAILS_SUCCESS = "SET_PLAYER_CARD_DETAILS_SUCCESS";
export const SET_PLAYER_CARD_DETAILS_FAILURE = "SET_PLAYER_CARD_DETAILS_FAILURE";

export const RESET_FETCH_MY_BETS_DETAILS_WATCHER = "RESET_FETCH_MY_BETS_DETAILS_WATCHER";
export const FETCH_MY_BETS_DETAILS_WATCHER = "FETCH_MY_BETS_DETAILS_WATCHER";
export const SET_MY_BETS_DETAILS_SUCCESS = "SET_MY_BETS_DETAILS_SUCCESS";
export const SET_MY_BETS_DETAILS_FAILURE = "SET_MY_BETS_DETAILS_FAILURE";

export const RESET_FETCH_SHARPSPORT_REMOVE_ACCOUNT_WATCHER = "RESET_FETCH_SHARPSPORT_REMOVE_ACCOUNT_WATCHER";
export const FETCH_SHARPSPORT_REMOVE_ACCOUNT_WATCHER = "FETCH_SHARPSPORT_REMOVE_ACCOUNT_WATCHER";
export const SET_SHARPSPORT_REMOVE_ACCOUNT_SUCCESS = "SET_SHARPSPORT_REMOVE_ACCOUNT_SUCCESS";
export const SET_SHARPSPORT_REMOVE_ACCOUNT_FAILURE = "SET_SHARPSPORT_REMOVE_ACCOUNT_FAILURE";

export const RESET_FETCH_PARLAY_DETAILS_WATCHER = "RESET_FETCH_PARLAY_DETAILS_WATCHER";
export const FETCH_PARLAY_DETAILS_WATCHER = "FETCH_PARLAY_DETAILS_WATCHER";
export const SET_PARLAY_DETAILS_SUCCESS = "SET_PARLAY_DETAILS_SUCCESS";
export const SET_PARLAY_DETAILS_FAILURE = "SET_PARLAY_DETAILS_FAILURE";

export const RESET_FETCH_SHORTS_DETAILS_WATCHER = "RESET_FETCH_SHORTS_DETAILS_WATCHER";
export const FETCH_SHORTS_DETAILS_WATCHER = "FETCH_SHORTS_DETAILS_WATCHER";
export const SET_SHORTS_DETAILS_SUCCESS = "SET_SHORTS_DETAILS_SUCCESS";
export const SET_SHORTS_DETAILS_FAILURE = "SET_SHORTS_DETAILS_FAILURE";

export const RESET_FETCH_GAME_TRENDS_DETAILS_WATCHER = "RESET_FETCH_GAME_TRENDS_DETAILS_WATCHER";
export const FETCH_GAME_TRENDS_DETAILS_WATCHER = "FETCH_GAME_TRENDS_DETAILS_WATCHER";
export const SET_GAME_TRENDS_DETAILS_SUCCESS = "SET_GAME_TRENDS_DETAILS_SUCCESS";
export const SET_GAME_TRENDS_DETAILS_FAILURE = "SET_GAME_TRENDS_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_GAME_TRENDS_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SPORT_GAME_TRENDS_DETAILS_WATCHER";
export const FETCH_SINGLE_SPORT_GAME_TRENDS_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_GAME_TRENDS_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_GAME_TRENDS_DETAILS_SUCCESS = "SET_SINGLE_SPORT_GAME_TRENDS_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_GAME_TRENDS_DETAILS_FAILURE = "SET_SINGLE_SPORT_GAME_TRENDS_DETAILS_FAILURE";

export const SET_GAME_TRENDS_FILTER = "SET_GAME_TRENDS_FILTER";
export const RESET_GAME_TRENDS_FILTER = "RESET_GAME_TRENDS_FILTER";

export const RESET_FETCH_PLAYER_TRENDS_DETAILS_WATCHER = "RESET_FETCH_PLAYER_TRENDS_DETAILS_WATCHER";
export const FETCH_PLAYER_TRENDS_DETAILS_WATCHER = "FETCH_PLAYER_TRENDS_DETAILS_WATCHER";
export const SET_PLAYER_TRENDS_DETAILS_SUCCESS = "SET_PLAYER_TRENDS_DETAILS_SUCCESS";
export const SET_PLAYER_TRENDS_DETAILS_FAILURE = "SET_PLAYER_TRENDS_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_WATCHER";
export const FETCH_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_SUCCESS = "SET_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_FAILURE = "SET_SINGLE_SPORT_PLAYER_TRENDS_DETAILS_FAILURE";

export const SET_PLAYER_TRENDS_FILTER = "SET_PLAYER_TRENDS_FILTER";
export const RESET_PLAYER_TRENDS_FILTER = "RESET_PLAYER_TRENDS_FILTER";

export const RESET_FETCH_ANDROID_BETSYNC_AMPLITUDE_DETAILS_WATCHER = "RESET_FETCH_ANDROID_BETSYNC_AMPLITUDE_DETAILS_WATCHER";
export const FETCH_ANDROID_BETSYNC_AMPLITUDE_DETAILS_WATCHER = "FETCH_ANDROID_BETSYNC_AMPLITUDE_DETAILS_WATCHER";
export const SET_ANDROID_BETSYNC_AMPLITUDE_DETAILS_SUCCESS = "SET_ANDROID_BETSYNC_AMPLITUDE_DETAILS_SUCCESS";
export const SET_ANDROID_BETSYNC_AMPLITUDE_DETAILS_FAILURE = "SET_ANDROID_BETSYNC_AMPLITUDE_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_RADIO_DETAILS_WATCHER = "RESET_FETCH_SINGLE_RADIO_DETAILS_WATCHER";
export const FETCH_SINGLE_RADIO_DETAILS_WATCHER = "FETCH_SINGLE_RADIO_DETAILS_WATCHER";
export const SET_SINGLE_RADIO_DETAILS_SUCCESS = "SET_SINGLE_RADIO_DETAILS_SUCCESS";
export const SET_SINGLE_RADIO_DETAILS_FAILURE = "SET_SINGLE_RADIO_DETAILS_FAILURE";
export const FETCH_SINGLE_RADIO_DETAILS_LOAD_MORE_WATCHER = "FETCH_SINGLE_RADIO_DETAILS_LOAD_MORE_WATCHER";
export const SET_SINGLE_RADIO_DETAILS_LOAD_MORE_SUCCESS = "SET_SINGLE_RADIO_DETAILS_LOAD_MORE_SUCCESS";
export const SET_SINGLE_RADIO_DETAILS_LOAD_MORE_FAILURE = "SET_SINGLE_RADIO_DETAILS_LOAD_MORE_FAILURE";

export const RESET_FETCH_TEAM_SCHEDULES_DETAILS_WATCHER = "RESET_FETCH_TEAM_SCHEDULES_DETAILS_WATCHER";
export const FETCH_TEAM_SCHEDULES_DETAILS_WATCHER = "FETCH_TEAM_SCHEDULES_DETAILS_WATCHER";
export const SET_TEAM_SCHEDULES_DETAILS_SUCCESS = "SET_TEAM_SCHEDULES_DETAILS_SUCCESS";
export const SET_TEAM_SCHEDULES_DETAILS_FAILURE = "SET_TEAM_SCHEDULES_DETAILS_FAILURE";

export const RESET_FETCH_TEAM_ROSTERS_DETAILS_WATCHER = "RESET_FETCH_TEAM_ROSTERS_DETAILS_WATCHER";
export const FETCH_TEAM_ROSTERS_DETAILS_WATCHER = "FETCH_TEAM_ROSTERS_DETAILS_WATCHER";
export const SET_TEAM_ROSTERS_DETAILS_SUCCESS = "SET_TEAM_ROSTERS_DETAILS_SUCCESS";
export const SET_TEAM_ROSTERS_DETAILS_FAILURE = "SET_TEAM_ROSTERS_DETAILS_FAILURE";

export const RESET_FETCH_SGP_CONTENT_DETAILS_WATCHER = "RESET_FETCH_SGP_CONTENT_DETAILS_WATCHER";
export const FETCH_SGP_CONTENT_DETAILS_WATCHER = "FETCH_SGP_CONTENT_DETAILS_WATCHER";
export const SET_SGP_CONTENT_DETAILS_SUCCESS = "SET_SGP_CONTENT_DETAILS_SUCCESS";
export const SET_SGP_CONTENT_DETAILS_FAILURE = "SET_SGP_CONTENT_DETAILS_FAILURE";

export const RESET_FETCH_ALL_SPORTS_SGP_CONTENT_DETAILS_WATCHER = "RESET_FETCH_ALL_SPORTS_SGP_CONTENT_DETAILS_WATCHER";
export const FETCH_ALL_SPORTS_SGP_CONTENT_DETAILS_WATCHER = "FETCH_ALL_SPORTS_SGP_CONTENT_DETAILS_WATCHER";
export const SET_ALL_SPORTS_SGP_CONTENT_DETAILS_SUCCESS = "SET_ALL_SPORTS_SGP_CONTENT_DETAILS_SUCCESS";
export const SET_ALL_SPORTS_SGP_CONTENT_DETAILS_FAILURE = "SET_ALL_SPORTS_SGP_CONTENT_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_SPORT_SGP_CONTENT_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SPORT_SGP_CONTENT_DETAILS_WATCHER";
export const FETCH_SINGLE_SPORT_SGP_CONTENT_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_SGP_CONTENT_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_SGP_CONTENT_DETAILS_SUCCESS = "SET_SINGLE_SPORT_SGP_CONTENT_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_SGP_CONTENT_DETAILS_FAILURE = "SET_SINGLE_SPORT_SGP_CONTENT_DETAILS_FAILURE";
export const FETCH_MORE_SGP_CONTENT_DETAILS_WATCHER = "FETCH_MORE_SGP_CONTENT_DETAILS_WATCHER";
export const SET_MORE_SGP_CONTENT_DETAILS_SUCCESS = "SET_MORE_SGP_CONTENT_DETAILS_SUCCESS";
export const SET_MORE_SGP_CONTENT_DETAILS_FAILURE = "SET_MORE_SGP_CONTENT_DETAILS_FAILURE";

export const RESET_FETCH_SHOW_VIDEO_DETAILS_WATCHER = "RESET_FETCH_SHOW_VIDEO_DETAILS_WATCHER";
export const FETCH_SHOW_VIDEO_DETAILS_WATCHER = "FETCH_SHOW_VIDEO_DETAILS_WATCHER";
export const SET_SHOW_VIDEO_DETAILS_SUCCESS = "SET_SHOW_VIDEO_DETAILS_SUCCESS";
export const SET_SHOW_VIDEO_DETAILS_FAILURE = "SET_SHOW_VIDEO_DETAILS_FAILURE";
export const FETCH_SHOW_VIDEO_DETAILS_LOAD_MORE_WATCHER = "FETCH_SHOW_VIDEO_DETAILS_LOAD_MORE_WATCHER";
export const SET_SHOW_VIDEO_DETAILS_LOAD_MORE_SUCCESS = "SET_SHOW_VIDEO_DETAILS_LOAD_MORE_SUCCESS";
export const SET_SHOW_VIDEO_DETAILS_LOAD_MORE_FAILURE = "SET_SHOW_VIDEO_DETAILS_LOAD_MORE_FAILURE";

export const FETCH_HOST_PICKS_DETAILS_WATCHER = "FETCH_HOST_PICKS_DETAILS_WATCHER";
export const SET_HOST_PICKS_DETAILS_SUCCESS = "SET_HOST_PICKS_DETAILS_SUCCESS";
export const SET_HOST_PICKS_DETAILS_FAILURE = "SET_HOST_PICKS_DETAILS_FAILURE";

export const FETCH_MORE_HOST_PICKS_DETAILS_WATCHER = "FETCH_MORE_HOST_PICKS_DETAILS_WATCHER";
export const SET_MORE_HOST_PICKS_DETAILS_SUCCESS = "SET_MORE_HOST_PICKS_DETAILS_SUCCESS";
export const SET_MORE_HOST_PICKS_DETAILS_FAILURE = "SET_MORE_HOST_PICKS_DETAILS_FAILURE";

export const FETCH_SINGLE_SPORT_HOST_PICKS_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_HOST_PICKS_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_HOST_PICKS_DETAILS_SUCCESS = "SET_SINGLE_SPORT_HOST_PICKS_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_HOST_PICKS_DETAILS_FAILURE = "SET_SINGLE_SPORT_HOST_PICKS_DETAILS_FAILURE";

export const FETCH_SINGLE_SPORT_MORE_HOST_PICKS_DETAILS_WATCHER = "FETCH_SINGLE_SPORT_MORE_HOST_PICKS_DETAILS_WATCHER";
export const SET_SINGLE_SPORT_MORE_HOST_PICKS_DETAILS_SUCCESS = "SET_SINGLE_SPORT_MORE_HOST_PICKS_DETAILS_SUCCESS";
export const SET_SINGLE_SPORT_MORE_HOST_PICKS_DETAILS_FAILURE = "SET_SINGLE_SPORT_MORE_HOST_PICKS_DETAILS_FAILURE";

export const RESET_FETCH_SEARCH_DETAILS_WATCHER = "RESET_FETCH_SEARCH_DETAILS_WATCHER";
export const FETCH_SEARCH_DETAILS_WATCHER = "FETCH_SEARCH_DETAILS_WATCHER";
export const SET_SEARCH_DETAILS_SUCCESS = "SET_SEARCH_DETAILS_SUCCESS";
export const SET_SEARCH_DETAILS_FAILURE = "SET_SEARCH_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_SHOW_DETAILS_WATCHER = "RESET_FETCH_SINGLE_SHOW_DETAILS_WATCHER";
export const FETCH_SINGLE_SHOW_DETAILS_WATCHER = "FETCH_SINGLE_SHOW_DETAILS_WATCHER";
export const SET_SINGLE_SHOW_DETAILS_SUCCESS = "SET_SINGLE_SHOW_DETAILS_SUCCESS";
export const SET_SINGLE_SHOW_DETAILS_FAILURE = "SET_SINGLE_SHOW_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_LEAGUE_DETAILS_WATCHER = "RESET_FETCH_SINGLE_LEAGUE_DETAILS_WATCHER";
export const FETCH_SINGLE_LEAGUE_DETAILS_WATCHER = "FETCH_SINGLE_LEAGUE_DETAILS_WATCHER";
export const SET_SINGLE_LEAGUE_DETAILS_SUCCESS = "SET_SINGLE_LEAGUE_DETAILS_SUCCESS";
export const SET_SINGLE_LEAGUE_DETAILS_FAILURE = "SET_SINGLE_LEAGUE_DETAILS_FAILURE";

export const RESET_FETCH_SINGLE_PODCAST_DETAILS_WATCHER = "RESET_FETCH_SINGLE_PODCAST_DETAILS_WATCHER";
export const FETCH_SINGLE_PODCAST_DETAILS_WATCHER = "FETCH_SINGLE_PODCAST_DETAILS_WATCHER";
export const SET_SINGLE_PODCAST_DETAILS_SUCCESS = "SET_SINGLE_PODCAST_DETAILS_SUCCESS";
export const SET_SINGLE_PODCAST_DETAILS_FAILURE = "SET_SINGLE_PODCAST_DETAILS_FAILURE";