export default {
    SomethingWentWrong: "Something went wrong. Please try again later.",
    ApiConnectionTimeout: "Please check your Internet Connection.",
    SessionExpiredTitle: "Warning",
    SessionExpiredMsg:
        "You have been logged out. Please login again to continue.",
    Error: "Error",
    InternetNotAvailableTitle: "Connection Problem",
    InternetNotAvailable: "Internet is not available",
    EmailBlank: "Email is Required",
    firstNameBlank: "First name is Required",
    lastNameBlank: "Last name is Required",
    EmailInvalid: "Please enter a valid email address",
    confirmPasswordNotMatched: "Confirm password is not matching",
    LogoutAlertTitle: "Logout",
    LogoutAlertMsg: "Do you want to Logout?",
    PasswordBlank: "Please enter a password",
    PasswordLength: "Your password must be at least 6 characters",
    PasswordStrong: "Must be 6 characters long with 1 capital letter and 1 number",
    ContentStartedmsg: "content started",
    FeedPageViewedmsg: "my feed viewed",
    gamesPageViewedmsg: "games viewed",
    watchPageViewedmsg: "watch viewed",
    picksPageViewedmsg: "picks viewed",
    ContentTypemsg: "content type",
    ContentTitlemsg: "content title",
    LoggedInmsg: "logged in",
    AccountCreatedmsg: "account created",
    matchupScreenViewedmsg: "matchup screen viewed",
    AppVersion: 'App Version: 1.0'
};